linters-settings:
   lll:
      line-length: 2380
   funlen:
      lines: 75
   errcheck:
      ignore : ""
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop 
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errname
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - gocognit
    - ineffassign
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - paralleltest
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - thelper
    - tparallel
    - unparam
    - unused
    - unconvert
    - unparam
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

  # don't enable:
  # - godox - maligned,prealloc
  # - gochecknoglobals
