version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    - dupl
    - errcheck
    - errname
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    errcheck:
      disable-default-exclusions: true
    funlen:
      lines: 75
    lll:
      line-length: 2380
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
