# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  #hooks:
    #post:
- goos:
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0
  main: ./cmd/github-actions/main.go
  binary: action
archives:
- format: binary
  replacements:
    linux: Linux
    amd64: x86_64
snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
release:
  github:
    owner: dictybase-docker
    name: github-actions
