name: Continuous build
on: 
 push:
   branches:
     - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: unit test
        run: go test -parallel 4 -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
  call-docker-build:
    needs: test
    uses: dictyBase/workflows/.github/workflows/docker-publish.yaml@main
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref_name }}
      image: github-actions
      dockerfile: build/package/Dockerfile 
