name: Create Pull Request
on: create
jobs:
  create-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get branch name
        id: vars
        run: |
          branch=$(echo ${{ github.ref }} | sed -r 's/refs\/heads\///')
          echo "branch_name=${branch}" >> $GITHUB_ENV
      - name: pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.WORKFLOW_RUN }}
          branch: ${{ env.branch_name }}
          base: develop
