name: Lint Golang code
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: false
      - name: run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.2
