name: Lint golang code 
on: 
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: run linter
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "-c .golangci.yml"

  binary:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.2
      - name: generate and publish binary 
        uses: goreleaser/goreleaser-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v0.138.0
          args: release --snapshot
