name: Release binary
on: 
  push:
    tags:
      - '*'
jobs:
  binary:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - name: generate and publish binary 
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest 
          args: release
