name: Release binary
on: 
  push:
    tags:
      - '*'
jobs:
  binary:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: generate and publish binary 
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@v6
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest 
          args: release --clean
  release-docker-build:
    needs: binary
    uses: dictyBase/workflows/.github/workflows/docker-cross-publish.yaml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      image: github-actions
      dockerfile: build/package/Dockerfile 
    secrets:
      dockeruser: ${{ secrets.DOCKERHUB_USER }}
      dockerpass: ${{ secrets.DOCKER_PASS }}
