name: Test coverage
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: check out code
        uses: actions/checkout@v4
      - name: unit test
        run: go test -parallel 4 -covermode=atomic -coverprofile=profile.cov -v ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
